string builds with eval

diff --git a/bdk-rep-buil b/bdk-rep-buil
--- a/bdk-rep-buil
+++ b/bdk-rep-buil
@@ -1,36 +1,41 @@
-#!/bin/bash
+#!/bin/sh
 
-# source ./targets.sh
 set -e
 
-
 bdkrepbuild__build() {
-    supported_libraries_keys=("bdk-flutter" "boltz-dart" "lwk-dart")
-    supported_libraries_urls=("https://github.com/LtbLightning/bdk-flutter" "https://github.com/SatoshiPortal/boltz-dart" "https://github.com/SatoshiPortal/lwk-dart")
+    if [ -z "$2" ]; then
+        echo "❌ You did not specify a build target! ❌"
+        usage=" 
+        USAGE
+            $ ./bdk-rep-build build <target>
 
-    # Function to get the repository URL
-    get_repo_url() {
-        local library_name="$1"
-        for i in "${!supported_libraries_keys[@]}"; do
-            if [[ "${supported_libraries_keys[i]}" == "$library_name" ]]; then
-                echo "${supported_libraries_urls[i]}"
-                return
-            fi
-        done
-        echo "Library not found"
+        EXAMPLE 
+            $ ./bdk-rep-build build linux"
+        echo "$usage"
+        exit 1  # Exit script with error code
+    fi
+
+    case "$2" in
+    "android" | "linux" | "macos" | "ios")
+        ;;
+    *)
+        echo "❌ Error: $2 is not a supported target. ❌"
+supported_targets="
+
+Supported targets are:
+        - linux 
+        - android
+        - macos
+        - ios "
+        echo "$supported_targets"
         exit 1
-    }
-    echo $2
-    echo $(get_repo_url $2)
-    # cd src/
-    # git clone $(get_repo_url $2)
-    # cd $2
+        ;;
+    esac
 
-    cd src/lwk-dart/cargokit/build_tool
-    # echo $external_var
-    eval "CARGOKIT_ROOT_PROJECT_DIR="/home/hkarani/Desktop/Projects/bdk-flutter-reproducible-build/src/lwk-dart/cargokit" CARGOKIT_TARGET_PLATFORM="linux-x64" CARGOKIT_CONFIGURATION="release" CARGOKIT_TARGET_TEMP_DIR="/home/hkarani/Desktop/Projects/bdk-flutter-reproducible-build/lib/linux" CARGOKIT_MANIFEST_DIR="/home/hkarani/Desktop/Projects/bdk-flutter-reproducible-build/src/lwk-dart/rust" CARGOKIT_OUTPUT_DIR="/home/hkarani/Desktop/Projects/bdk-flutter-reproducible-build/release/linux" dart run build_tool build-cmake"
 
-    echo "$2 target build for $3 complete "
+    target=$2   
+    export target
+    . "./$target.sh"
 }
 
 bdkrepbuild__help_build(){
@@ -51,9 +56,39 @@ echo "$help"
 
 
 bdkrepbuild__verify(){
- echo "downnloading $2"
- echo "checking out $3"
- echo "building $4"
+    if [ -z "$2" ]; then
+        echo "❌ You did not specify a target to verify! ❌"
+        usage=" 
+        USAGE
+            $ ./bdk-rep-build verify <target>
+
+        EXAMPLE 
+            $ ./bdk-rep-build verify linux"
+        echo "$usage"
+        exit 1  # Exit script with error code
+    fi
+
+    case "$2" in
+    "android" | "linux" | "macos" | "ios")
+        ;;
+    *)
+        echo "❌ Error: $2 is not a supported target you can verify. ❌"
+    supported_targets="
+
+Supported targets are:
+        - linux 
+        - android
+        - macos
+        - ios"
+        echo "$supported_targets"
+        exit 1
+        ;;
+    esac
+
+    target="$2"   
+    export $target
+
+    . ./verifier.sh
 
 }
 
