Statically build github binary links

diff --git a/bdk-rep-build b/bdk-rep-build
--- a/bdk-rep-build
+++ b/bdk-rep-build
@@ -297,24 +297,38 @@ bdkrepbuild__verify(){
         ;;
     esac
 
+    case "$target" in
+    "x86_64-unknown-linux-gnu") binary_name="x86_64-unknown-linux-gnu.so" ;;
+    "aarch64-unknown-linux-gnu") binary_name="aarch64-unknown-linux-gnu.so" ;;
+    "x86_64-apple-darwin") binary_name="x86_64-apple-darwin.a" ;;
+    "aarch64-apple-darwin") binary_name="aarch64-apple-darwin.a" ;;
+    "aarch64-apple-ios") binary_name="aarch64-apple-ios.a" ;;
+    "aarch64-apple-ios-sim") binary_name="aarch64-apple-ios-sim.a" ;;
+    "x86_64-apple-ios") binary_name="x86_64-apple-ios.a" ;;
+    "aarch64-linux-android") binary_name="aarch64-linux-android.so" ;;
+    "i686-linux-android") binary_name="i686-linux-android.so" ;;
+    "x86_64-linux-android") binary_name="x86_64-linux-android.so" ;;
+    "armv7-linux-androideabi") binary_name="armv7-linux-androideabi.so" ;;
+    *) echo "Error: Unsupported target '$target'"; exit 1 ;;
+    esac
     # Set variables
     REPO="hkarani/$library"
     DESTINATION="release/published/$library/$VERSION/$target"
     mkdir -p $DESTINATION  # Change this to your desired location
 
     # Fetch the filename dynamically
-    FILE_URL=$(curl -s "https://api.github.com/repos/$REPO/releases/tags/$VERSION" | \
-    sed -n 's/.*"browser_download_url": "\(.*\/'"$target"'[^"]*\)".*/\1/p' | head -n 1)
+    FILE_URL="https://github.com/$REPO/releases/download/$VERSION/$binary_name"
 
     # Check if a file was found
     if [[ -z "$FILE_URL" ]]; then
-    echo "No matching file found for target: $target"
-    exit 1
+        echo "No matching file found for target: $target"
+        echo $FILE_URL
+        exit 1
     fi
 
+   
     # Extract filename
     FILENAME=$(basename "$FILE_URL")
-
     # Download the file
     curl -L -o "$DESTINATION/$FILENAME" "$FILE_URL" >/dev/null 2>&1
 
@@ -330,8 +344,6 @@ bdkrepbuild__verify(){
     # export $target
 
     . ./verifier.sh $library $target $downloaded_file $VERSION
-    echo "Verifying $target for $library library, version $VERSION"
-
 }
 
 bdkrepbuild__help_verify() {
